### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by tricantivu**
Hi :wave:, this is a very minimalist and interesting project.

I edited `bashbar`'s main file and improved some things here and there. I hope they're of value

### CODE REVIEW

**Comment by wick3dr0se** [comment]
Sorry man there is a few changes I wouldn't want to see at all and I have some coding prefrences with bash.

- `printf` in all cases is quicker than `echo`
- set -E makes error handling more consistent
- set -o pipefail keeps errors from continuing in a pipeline
- using regex to check for > 100 isn't a great method and will cause more overhead

The rest is just prefrence like how I stick pipe ans logical operators onto the end of a condition and how I space around conditions in arithmetic evaluation but don't if it's not to test. I really don't like using `set` much at all and probably will just remove that entirely. I'll rewrite this soon because I'm not a fan of how it creates new bars. Have to work on a better implementation

**Comment by tricantivu** [comment]
Hi @wick3dr0se, thanks for taking the time to review the commits. Although I have some thoughts about your points.

### `printf` is not always faster than `echo`, for example:

*Script 1*

```shell
#!/usr/bin/env bash

for n in {1..1000000}; do
       
    echo "${n}"

done
```

*Script 2*

```shell
#!/usr/bin/env bash

for n in {1..1000000}; do
     
     printf '%d\n' "${n}"

done
```

Timing the elapsed real time of each script using GNU `time` 1.9, the former runs in 2.46 seconds while the latter finishes in 3.04. Furthermore, averaging five runs, `echo` remains the winner with 2.65 seconds (2.56, 3.07, 2.55, 2.53, 2.54) whereas `printf` stays with 3.13 (3.03, 3.33, 3.02, 3.17, 3.09).

[printf](https://git.savannah.gnu.org/cgit/bash.git/tree/builtins/printf.def) is hundreds of lines longer than [echo](https://git.savannah.gnu.org/cgit/bash.git/tree/builtins/echo.def). `wc` counts 202 and 1355 lines respectively.

### Regex

If it doesn't cut it, maybe arithmetic operators will:

`(( $1 >= 1 && $1 <= 100 )) || ...`

### `pipefail`

Why set it if there are no pipelines?

And what do you mean by the `-E` option making error handling more consistent?

**Comment by tricantivu** [comment]
As promised, I edited my commits to follow what we agreed on.

I noticed you write command groups in the same line, so I followed such style in
one of my commits.

The regular expression to validate `$1` was replaced for arithmetic evaluation.
You were right about the overhead, it did not take into account numbers in other
bases (*i.e* `0x20`).

**Comment by wick3dr0se** [comment]
@tricantivu Awesome, thanks a lot man! I'm not sure why commits can't be updated here and then I could just reopen the PR.. If you want to open a new PR with the changes, I will gladly accept!

**Pull request closed without merging**
